[package]
name = "ssh-proxy-api"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9"
actix-web = "2"
actix-rt = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
failure = "0.1"
env_logger = "0.7"
